# Auto-generated file by setup.py build_factory

from pymt.factory import Factory

Factory.register('EventDispatcher', module='pymt.event')
Factory.register('SafeList', module='pymt.utils')
Factory.register('MTContext', module='pymt.plugin')
Factory.register('MTPlugins', module='pymt.plugin')
Factory.register('BaseObject', module='pymt.baseobject')
Factory.register('ExceptionHandler', module='pymt.exceptions')
Factory.register('ExceptionManager', module='pymt.exceptions')
Factory.register('OBJ', module='pymt.obj')
Factory.register('Material', module='pymt.obj')
Factory.register('MaterialGroup', module='pymt.obj')
Factory.register('Mesh', module='pymt.obj')
Factory.register('FactoryException', module='pymt.factory')
Factory.register('Vector', module='pymt.vector')
Factory.register('ProxyImage', module='pymt.loader')
Factory.register('Texture', module='pymt.texture')
Factory.register('TextureRegion', module='pymt.texture')
Factory.register('Cache', module='pymt.cache')
Factory.register('LoggerHistory', module='pymt.logger')
Factory.register('Gesture', module='pymt.gesture')
Factory.register('GestureDatabase', module='pymt.gesture')
Factory.register('GesturePoint', module='pymt.gesture')
Factory.register('GestureStroke', module='pymt.gesture')
Factory.register('TouchProvider', module='pymt.input.provider')
Factory.register('TouchFactory', module='pymt.input.factory')
Factory.register('TouchShape', module='pymt.input.shape')
Factory.register('TouchShapeRect', module='pymt.input.shape')
Factory.register('Widget', module='pymt.uix.widget')
